### ISSUE TITLE
Box doesn't handle default values

### ISSUE THREAD

**Issue by DethRaid** [Alloyed/imgui-bindings#1]
Opening an issue for what I talked about on Discord

When I call `ImGui.Begin` with only one argument, I get a crash

After some investigation, it seems that the native implementation of `ImGui.Begin` tries to dereference a pointer in the seconds Wren VM slot without performing any kind of null checks. I have to provide an argument for all the parameters for `ImGui.Begin` to avoid the crash

After some discussion on Discord, the issue seems to be that Box doesn't have a default variant defined, so it explodes when given an invalid value

**Comment by Alloyed** [comment]
Fixed by 961432b. The actual code output in this case is a bit tortured :( but it works
```c++
	bool* p_open = NULL;
	bool p_open_box;
	if(!wrenExIsSlotDefault(vm, 1)) {
		p_open_box = Box::getCPP<bool>(vm, 1);
		p_open = &p_open_box;
	}
	
	ImGui::ShowDemoWindow(p_open);
	
	if(p_open) { Box::setCPP<bool>(vm, 1, *p_open); }
```
