### ISSUE TITLE
Crash when setting window size

### ISSUE THREAD

**Issue by DethRaid** [Alloyed/imgui-bindings#2]
Consider the following code:
```wren
draw() {
    var pos = ImVec2.new(300, 300)
    var pivot = ImVec2.new(0.5, 0.5)
    ImGui.SetNextWindowPos(pos, "Always", pivot)

    ImGui.Begin("Environment Object", Box.new(true), 0)
    ImGui.Text("This is where the object stuff will go")
    ImGui.End()
}
```
I'm trying to put my ImGUI window in the middle of the screen. However, creating an `ImVec2` causes a crash in the Wren VM. It _seems_ to be something about not being able to find the constructor for `Imvec2`? But I don't know Wren VM internals well enough to really diagnose this

When I comment everything out except the creation of the variable `pos`, I still get the crash. When I remove `pos`, `pivot`, and the call to `ImGui.SetNextWindowPos`, I do not get the crash
```wren
draw() {
    ImGui.Begin("Environment Object", Box.new(true), 0)
    ImGui.Text("This is where the object stuff will go")
    ImGui.End()
}
```
This code works - but my ImGui window is in the wrong place

**Comment by Alloyed** [comment]
my bad~ this is a case where I wrote up ImVec2 and pushed it without testing, hopefully this fixes the issue

**Comment by DethRaid** [comment]
Can confirm that this works. Thank you so much!
